# This is a basic workflow to help you get started with Actions

name: test-install

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pacaptr:
    runs-on: macos-latest
    steps:
      # - uses: actions/checkout@v2
      - run: brew test-bot